### ISSUE TITLE
C Programming // Program to convert binary number to decimal

### ISSUE THREAD

**Issue by tsuyoshi007** [tsuyoshi007/KIT-Batch-6B#28]
Desired Output: 
---------------------------------------------------
|Enter a binary number: 110110111
|110110111 in binary = 439
----------------------------------------------------

**Comment by klutz2121** [comment]
Leave it to me^_^

**Comment by VisalYun** [comment]
Make a condition that user can only input 1 and 0
If user inputs other number, mark as error

**Comment by lychunvira18** [comment]
I'll try taking this up.
