### ISSUE TITLE
Web Design/Navigation_bar // create a navigation using html and css

### ISSUE THREAD

**Issue by tsuyoshi007** [tsuyoshi007/KIT-Batch-6B#30]
-Create a navigation bar
-Don't need to put the same logo

Desired Output:

![53871240_153214315619647_2807715392359759872_n](https://user-images.githubusercontent.com/45678324/53856121-46e4f380-4003-11e9-8ca5-836941431f44.png)

After move mouse on the logo:

![53389163_2243249835940337_6449665393840619520_n](https://user-images.githubusercontent.com/45678324/53856124-48162080-4003-11e9-8d86-c2715815204e.png)

**Comment by SokhonC** [comment]
Dear god. and all 
I am going to take this issues.
