### ISSUE TITLE
C Programming/Program to convert Decimal to Hexa-Decimal

### ISSUE THREAD

**Issue by sokhomsovichea** [tsuyoshi007/KIT-Batch-6B#40]
expected output:
\-----------------------------------------------------\
\Please Enter the Decimal Number to convert:     \
\-----------------------------------------------------\
\Decimal: n                                                            \
\Hexa-Decimal:                                                      \
\-----------------------------------------------------\

**Comment by klutz2121** [comment]
I shall take this.
