### ISSUE TITLE
C Programming/ Program to convert Decimal to Octa Decimal

### ISSUE THREAD

**Issue by sokhomsovichea** [tsuyoshi007/KIT-Batch-6B#43]
expected output:
\----------------------------------------------------\
\Please Enter the Decimal Number to convert:    \
\----------------------------------------------------\
\Decimal: n                                                           \
\Hexa-Decimal:                                                     \
\----------------------------------------------------\

**Comment by NeupOrng** [comment]
i take it

**Comment by NeupOrng** [comment]
it done merge it
