### ISSUE TITLE
C programming/decimal to Binary and Hexa and Octal 

### ISSUE THREAD

**Issue by VisalYun** [tsuyoshi007/KIT-Batch-6B#44]
Accept decimal value and let your code do it
--------Output-----------
Decimal: 10
----------------
Binary: 1010
Hexa-Decimal: A
Octal: 12

---->Note: Please understand decimal to binary, decimal to Hexa, decimal to Octal first before get hand on this project

**Comment by lychunvira18** [comment]
I'll take on this issue.
