### ISSUE TITLE
C programing//Create Christmas Tree with Asterisk

### ISSUE THREAD

**Issue by sokhomsovichea** [tsuyoshi007/KIT-Batch-6B#52]

**Comment by suthirakprom** [comment]
#include<stdio.h>
int main ()
{
    int rows,a,b,c;
    printf("Enter a number of rows:");
    scanf("%d",&rows);
    c=rows-1;
    for(b=c;b>=1;b--)
    {
        for(a=rows;a>=1;a--)
            c--;
        printf("");
        for(a=2*(rows-b)-1;a>=1;a--)
            printf("*",a);
        printf("\n");
        c -= 1;
    }
    return 0;
}

**Comment by suthirakprom** [comment]
copied from the internet btw ;)
