### ISSUE TITLE
Web Design/Vanilla HTML,CSS,JS//Duplicate Facebook Signup page

### ISSUE THREAD

**Issue by lychunvira18** [tsuyoshi007/KIT-Batch-6B#74]
## Duplicate *Facebook* signup page!
Try your best to duplication https://www.facebook.com on only it's Signup page. 
Doesn't need to be 100% accurate.
> You can also use your own designs! **GO WILD!**

**Challenge:** 
- Make it responsive

**Comment by DoungKolBondith** [comment]
I will try it .Thank sir for making my life brightness before i don't know what project i need to do but when i join your company i have so many things to do thank sir again 😍
