### ISSUE TITLE
Web Design/Responsive page // make it responsive

### ISSUE THREAD

**Issue by tsuyoshi007** [tsuyoshi007/KIT-Batch-6B#8]
try to zoom you will see the problem
problem: 
-try make it more responsive (it's not responsive in smartphone )
-bug when we zoom

**Comment by lychunvira18** [comment]
The problem of the zoom issue is probably related to the margins in the CSS files.

**Comment by VikranCutties** [comment]
Thank sir!!!

**Comment by VikranCutties** [comment]
I can't do it sir!! Can I resign???
