### ISSUE TITLE
C Programming/phonebook.c // add a function that can save phone number to a txt file

### ISSUE THREAD

**Issue by tsuyoshi007** [tsuyoshi007/KIT-Batch-6B#9]

**Comment by VikranCutties** [comment]
roger that!!!

**Comment by tsuyoshi007** [comment]
wtf T_T

**Comment by tsuyoshi007** [comment]
this is the output that i want !!!!
![image](https://user-images.githubusercontent.com/45678324/53082672-edbf8f00-352f-11e9-9d67-d4b4c4be588f.png)
